spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to MyBank accounts related QA APIs"
  contactDetails:
    name: "John Doe- Senior Developer"
    email: "john@info.com"
  onCallSupport:
    - (555)555-258
    - (555)523-684
